blank_issues_enabled: false

contact_links:
  - name: ðŸ“š Read the Wiki
    url: https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/wiki
    about: Find usage guides, module setup instructions, and FAQs here.

  - name: ðŸ’¬ Discord Thread (Pathfinder on FoundryVTT Discord)
    url: https://discord.com/channels/880968862240239708/1318068254945574962
    about: Need help or want to contribute translations? Come chat with us!
